//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naming.
        /// </summary>
        internal static string AG_1_Category {
            get {
                return ResourceManager.GetString("AG.1.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint must have Route attribute to be registered in API..
        /// </summary>
        internal static string AG_1_Description {
            get {
                return ResourceManager.GetString("AG.1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint &apos;{0}&apos; must have Route attibute..
        /// </summary>
        internal static string AG_1_MessageFormat {
            get {
                return ResourceManager.GetString("AG.1.MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint must have Route attribute..
        /// </summary>
        internal static string AG_1_Title {
            get {
                return ResourceManager.GetString("AG.1.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naming.
        /// </summary>
        internal static string AG_2_Category {
            get {
                return ResourceManager.GetString("AG.2.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint must have Get method be registered in API..
        /// </summary>
        internal static string AG_2_Description {
            get {
                return ResourceManager.GetString("AG.2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint &apos;{0}&apos; must have Get method..
        /// </summary>
        internal static string AG_2_MessageFormat {
            get {
                return ResourceManager.GetString("AG.2.MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint must have Get method..
        /// </summary>
        internal static string AG_2_Title {
            get {
                return ResourceManager.GetString("AG.2.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naming.
        /// </summary>
        internal static string AG_3_Category {
            get {
                return ResourceManager.GetString("AG.3.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint method Get should follow naming conventions..
        /// </summary>
        internal static string AG_3_Description {
            get {
                return ResourceManager.GetString("AG.3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint &apos;{0}&apos; method &apos;{1}&apos; should be named &apos;{2}&apos;..
        /// </summary>
        internal static string AG_3_MessageFormat {
            get {
                return ResourceManager.GetString("AG.3.MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint method Get should follow naming conventions..
        /// </summary>
        internal static string AG_3_Title {
            get {
                return ResourceManager.GetString("AG.3.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naming.
        /// </summary>
        internal static string AG_4_Category {
            get {
                return ResourceManager.GetString("AG.4.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint method attibutes should match route parameters..
        /// </summary>
        internal static string AG_4_Description {
            get {
                return ResourceManager.GetString("AG.4.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint &apos;{0}&apos; method &apos;{1}&apos; argument &apos;{2}&apos; should be in route &apos;{3}&apos;..
        /// </summary>
        internal static string AG_4_MessageFormat {
            get {
                return ResourceManager.GetString("AG.4.MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint method attibutes should match route parameters..
        /// </summary>
        internal static string AG_4_Title {
            get {
                return ResourceManager.GetString("AG.4.Title", resourceCulture);
            }
        }
    }
}
